version: 0.1
log:
  fields:
    service: registry
storage:
  ipfs:
    direction: in
    address: 172.17.0.1:5000
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: Registry Realm
    path: /auth/htpasswd