version: 0.1
log:
  fields:
    service: registry
storage:
  ipfs:
    direction: download
    address: ipfs:5000
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: Registry Realm
    path: /auth/htpasswd
